// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKN0PlJo3JJYAMpSwNL4dI_YC2ESbKfCs',
    appId: '1:333264671887:web:217e29c6123145f47e8cfa',
    messagingSenderId: '333264671887',
    projectId: 'sarvagya-a31fc',
    authDomain: 'sarvagya-a31fc.firebaseapp.com',
    storageBucket: 'sarvagya-a31fc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZDs3-heyj4mr2Jn8uIQulfLleM0NYSaM',
    appId: '1:333264671887:android:e4537059fd8517347e8cfa',
    messagingSenderId: '333264671887',
    projectId: 'sarvagya-a31fc',
    storageBucket: 'sarvagya-a31fc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9JxNHpayG_8O40dQ761ucCYvaqLKrK6Y',
    appId: '1:333264671887:ios:76ed2f949ee4c2137e8cfa',
    messagingSenderId: '333264671887',
    projectId: 'sarvagya-a31fc',
    storageBucket: 'sarvagya-a31fc.appspot.com',
    iosClientId: '333264671887-5g1arfs18mkqnergld1phcfogkj3t8lk.apps.googleusercontent.com',
    iosBundleId: 'com.example.sarvagya',
  );
}
